language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt
  - coverage erase

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.test_settings"

services:
  - postgresql

script:
  - coverage run ./manage.py test tests.apps --settings=pur_beurre.settings.test_settings

# safelist
branches:
  only:
    - staging
